import { Game } from "@local/classes";

export default [
    {
        Constructor: Game.MeshStandardMaterial,
        label: "3D Standard Material",
        attributes: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "emissive",
            "emissiveIntensity",
            "roughness",
            "metalness",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "lightMap",
            "lightMapIntensity",
            "emissiveMap",
            "metalnessMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "roughnessMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    },
    {
        Constructor: Game.MeshPhysicalMaterial,
        label: "Physical Material",
        attributes: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "attenuationColor",
            "thickness",
            "transmission",
            "side",
            "emissive",
            "emissiveIntensity",
            "roughness",
            "reflectivity",
            "metalness",
            "clearcoat",
            "clearcoatRoughness",
            "clearcoatNormalMap",
            "clearcoatNormalScale.x",
            "clearcoatNormalScale.y",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "lightMap",
            "lightMapIntensity",
            "emissiveMap",
            "metalnessMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "roughnessMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    },
    {
        Constructor: Game.LineBasicMaterial,
        label: "Line Basic Material",
        attributes: ["type", "name", "uuid"]
    },
    {
        Constructor: Game.LineDashedMaterial,
        label: "Line Dashed Material",
        attributes: ["type", "name", "uuid"]
    },
    {
        Constructor: Game.MeshBasicMaterial,
        label: "Basic Material",
        attributes: [
            "list",
            "type",
            "name",
            "uuid",
            "side",
            "color",
            "vortexColors",
            "opacity",
            "alphaTest",
            "depthWrite",
            "reflectivity",
            "depthTest",
            "blending",
            "map",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "alphaMap",
            "lightMap",
            "lightMapIntensity",
            "specularMap"
        ]
    },
    {
        Constructor: Game.MeshDepthMaterial,
        label: "Depth Material",
        attributes: ["type", "name", "uuid"]
    },
    {
        Constructor: Game.MeshLambertMaterial,
        label: "Lambert Material",
        attributes: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "emissive",
            "emissiveIntensity",
            "reflectivity",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "lightMap",
            "lightMapIntensity",
            "emissiveMap",
            "specularMap",
            "map"
        ]
    },
    {
        Constructor: Game.MeshMatcapMaterial,
        label: "Matcap Material",
        attributes: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "matcap",
            "bumpMap",
            "bumpScale",
            "normalMap",
            "normalScale.x",
            "normalScale.y",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "map"
        ]
    },
    {
        Constructor: Game.MeshPhongMaterial,
        label: "Blinn-Phong Material",
        attributes: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "specular",
            "shininess",
            "side",
            "emissive",
            "emissiveIntensity",
            "reflectivity",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "emissiveMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "normalMap",
            "normalScale.x",
            "normalScale.y",
            "specularMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    },
    {
        Constructor: Game.MeshToonMaterial,
        label: "Cartoon Material",
        attributes: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "emissive",
            "emissiveIntensity",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "emissiveMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "normalMap",
            "normalScale.x",
            "normalScale.y",
            "lightMap",
            "lightMapIntensity",
            "gradientMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    }
];