export default [
    {
        className: "MeshStandardMaterial",
        label: "Material 3D Padão",
        props: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "emissive",
            "emissiveIntensity",
            "roughness",
            "metalness",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "lightMap",
            "lightMapIntensity",
            "emissiveMap",
            "metalnessMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "roughnessMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    },
    {
        className: "MeshPhysicalMaterial",
        label: "Material Físico",
        props: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "attenuationColor",
            "thickness",
            "transmission",
            "side",
            "emissive",
            "emissiveIntensity",
            "roughness",
            "reflectivity",
            "metalness",
            "clearcoat",
            "clearcoatRoughness",
            "clearcoatNormalMap",
            "clearcoatNormalScale.x",
            "clearcoatNormalScale.y",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "lightMap",
            "lightMapIntensity",
            "emissiveMap",
            "metalnessMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "roughnessMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    },
    {
        className: "LineBasicMaterial",
        label: "Linha Comum",
        props: ["type", "name", "uuid"]
    },
    {
        className: "LineDashedMaterial",
        label: "Linha Tracejada",
        props: ["type", "name", "uuid"]
    },
    {
        className: "MeshBasicMaterial",
        label: "Material Básico",
        props: [
            "list",
            "type",
            "name",
            "uuid",
            "side",
            "color",
            "vortexColors",
            "opacity",
            "alphaTest",
            "depthWrite",
            "reflectivity",
            "depthTest",
            "blending",
            "map",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "alphaMap",
            "lightMap",
            "lightMapIntensity",
            "specularMap"
        ]
    },
    {
        className: "MeshDepthMaterial",
        label: "Material de Profundidade",
        props: ["type", "name", "uuid"]
    },
    {
        className: "MeshLambertMaterial",
        label: "Material Lambertiano",
        props: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "emissive",
            "emissiveIntensity",
            "reflectivity",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "lightMap",
            "lightMapIntensity",
            "emissiveMap",
            "specularMap",
            "map"
        ]
    },
    {
        className: "MeshMatcapMaterial",
        label: "Material Matcap",
        props: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "matcap",
            "bumpMap",
            "bumpScale",
            "normalMap",
            "normalScale.x",
            "normalScale.y",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "map"
        ]
    },
    {
        className: "MeshPhongMaterial",
        label: "Material de Blinn-Phong",
        props: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "specular",
            "shininess",
            "side",
            "emissive",
            "emissiveIntensity",
            "reflectivity",
            "flatShading",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "envMap",
            "emissiveMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "normalMap",
            "normalScale.x",
            "normalScale.y",
            "specularMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    },
    {
        className: "MeshToonMaterial",
        label: "Material Cartoonizado",
        props: [
            "list",
            "type",
            "name",
            "uuid",
            "color",
            "side",
            "emissive",
            "emissiveIntensity",
            "vortexColors",
            "blending",
            "opacity",
            "alphaTest",
            "depthTest",
            "depthWrite",
            "alphaMap",
            "aoMap",
            "aoMapIntensity",
            "emissiveMap",
            "displacementMap",
            "displacementBias",
            "displacementScale",
            "normalMap",
            "normalScale.x",
            "normalScale.y",
            "lightMap",
            "lightMapIntensity",
            "gradientMap",
            "bumpMap",
            "bumpScale",
            "map"
        ]
    }
];